# Generated by Django 4.2.7 on 2023-11-15 03:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('head_office', models.CharField(max_length=100)),
                ('access_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
    ]
