# Generated by Django 4.2.7 on 2024-01-29 01:27

from django.db import migrations, models
import user.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerifiedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50)),
                ('nid_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('birth_date_bs', models.DateField()),
                ('nationality', models.CharField(max_length=30)),
                ('citizenship_number', models.CharField(max_length=20, unique=True)),
                ('citizen_issued_district', models.CharField(max_length=50)),
                ('citizen_issued_date_bs', models.DateField()),
                ('photo', models.ImageField(upload_to=user.models.upload_photo)),
                ('citizenship_front', models.ImageField(upload_to=user.models.upload_cit_front)),
                ('citizenship_back', models.ImageField(upload_to=user.models.upload_cit_back)),
                ('permanent_address_district', models.CharField(max_length=50)),
                ('permanent_address_municipality', models.CharField(max_length=50)),
                ('permanent_address_ward', models.CharField(max_length=50)),
                ('permanent_address_tol', models.CharField(max_length=100)),
                ('current_address_district', models.CharField(max_length=50)),
                ('current_address_municipality', models.CharField(max_length=50)),
                ('current_address_ward', models.CharField(max_length=50)),
                ('current_address_tol', models.CharField(max_length=100)),
                ('signature', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('regulator', 'Admin'), ('bank', 'Bank')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
