# Generated by Django 4.2.7 on 2023-11-15 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VerifiedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('nid_number', models.CharField(blank=True, max_length=20, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('birth_date_bs', models.DateField()),
                ('nationality', models.CharField(max_length=30)),
                ('citizenship_number', models.CharField(max_length=20, unique=True)),
                ('citizen_issued_district', models.CharField(max_length=50)),
                ('citizen_issued_date_bs', models.DateField()),
                ('permanent_address_district', models.CharField(max_length=50)),
                ('permanent_address_municipality', models.CharField(max_length=50)),
                ('permanent_address_ward', models.CharField(max_length=50)),
                ('permanent_address_tol', models.CharField(max_length=100)),
                ('current_address_district', models.CharField(max_length=50)),
                ('current_address_municipality', models.CharField(max_length=50)),
                ('current_address_ward', models.CharField(max_length=50)),
                ('current_address_tol', models.CharField(max_length=100)),
            ],
        ),
    ]
