# Generated by Django 4.2.7 on 2024-01-28 09:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_verifieduser_signautre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifieduser',
            name='signautre',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
