# Generated by Django 4.2.7 on 2024-01-28 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_verifieduser_signautre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifieduser',
            name='nid_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
