# Generated by Django 4.2.7 on 2024-01-28 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_verifieduser_nid_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifieduser',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
