# Generated by Django 4.2.7 on 2024-01-28 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_rename_signautre_verifieduser_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifieduser',
            name='citizenship_back',
            field=models.ImageField(upload_to=None),
        ),
        migrations.AlterField(
            model_name='verifieduser',
            name='citizenship_front',
            field=models.ImageField(upload_to=None),
        ),
        migrations.AlterField(
            model_name='verifieduser',
            name='photo',
            field=models.ImageField(upload_to=None),
        ),
    ]
